version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

brews:
  - repository:
      owner: fishfisher
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    homepage: https://github.com/fishfisher/apple-contacts
    description: "CLI for searching and querying Apple Contacts via AppleScript"
    install: |
      bin.install "apple-contacts"
    test: |
      system "#{bin}/apple-contacts", "--help"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"
